modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="https://github.com/Christofmeg/AE2-QoL-Recipes/issues"
license="${license}"
[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    displayURL="https://github.com/Christofmeg/AE2-QoL-Recipes"
    logoFile="icon.png"
    authors="${mod_authors}"
    description='''${description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[modproperties.${mod_id}]
    catalogueItemIcon="ae2:fluix_glass_cable"